#!/usr/bin/env php
<?php

use EasySwoole\EasySwoole\Command\CommandRunner;

defined('IN_PHAR') or define('IN_PHAR', boolval(\Phar::running(false)));
defined('RUNNING_ROOT') or define('RUNNING_ROOT', realpath(getcwd()));
defined('EASYSWOOLE_ROOT') or define('EASYSWOOLE_ROOT', IN_PHAR ? \Phar::running() : realpath(getcwd()));

#是否开启日志
define('DEBUG_LOG', true);

$file = EASYSWOOLE_ROOT.'/vendor/autoload.php';
if (file_exists($file)) {
    require $file;
}else{
    die("include composer autoload.php fail\n");
}

if(file_exists(EASYSWOOLE_ROOT.'/bootstrap.php')){
    require_once EASYSWOOLE_ROOT.'/bootstrap.php';
}

$args = $argv;
//trim first command
array_shift($args);

$ret = CommandRunner::getInstance()->run($args);
if(!empty($ret)){
    echo $ret."\n";
}

//是否开始日志写入功能
function writeLog($msg, $open = false) {
    //开启日记
    if ($open === DEBUG_LOG) {
        return ;
    }
    $logPath =  EASYSWOOLE_ROOT . '/Log/db-' . date('Y-m-d').'.log';
    if( !file_exists($logPath) ) {
        $fp = fopen( $logPath,'w');
        fclose( $fp );
    }
    error_log( date('Y-m-d H:i:s', time()) .' | exec sql : ' . $msg.PHP_EOL, 3, $logPath);
}