<?php

namespace App\HttpController\User\Controller;

use App\HttpController\Common\BaseController;

class Admin extends BaseController
{

    public $access = [
        '*' => ['admin']
    ];

    /**
     * 初始化设置
     * @param string|null $action
     * @return bool|null
     */
    public function onRequest(?string $action): ?bool
    {
         return parent::onRequest($action); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        $this->writeJson(200, 'index', 'success');
    }

    /**
     * 分类检索
     */
    public function search()
    {
        $this->writeJson(200, 'search', 'success');
    }

    /**
     * 列表
     */
    public function list()
    {
        $this->writeJson(200, 'list', 'success');
    }

    /**
     * 创建
     */
    public function create()
    {
        $this->writeJson(200, 'create', 'success');
    }

    /**
     * 查看
     */
    public function view()
    {
        $this->writeJson(200, 'view', 'success');
    }

    /**
     * 删除
     */
    public function delete()
    {
        $this->writeJson(200, 'delete', 'success');
    }
}