<?php
namespace App\HttpController\User;

use App\HttpModel\User\UserModel;
use EasySwoole\Http\AbstractInterface\Controller;


class User extends Controller
{
    public function onRequest(?string $action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    public function actionNotFound(?string $action)
    {
        parent::actionNotFound($action); // TODO: Change the autogenerated stub
    }

    public function requestTotal()
    {
        $this->response()->write('请求数+1'.PHP_EOL);
        // 还可以return，但不要两个方法互相调用，会死循环
    }

    public function userInfo()
    {
        // 获取get参数
        $id = $this->request()->getQueryParam('id');
        // 输出到终端
        var_dump($id);
        // 返回给客户端
        $this->response()->write($id.PHP_EOL);
    }

    public function create()
    {
        $model = new UserModel();
        $model::create([
            'username' => 'whldk',
            'password' => md5('123456'),
            'real_name' => 'whldk'
        ]);
        $res = $model->save();
        $this->response()->write($res.PHP_EOL);
    }

}