<?php namespace App\HttpController;

use App\HttpController\Common\Controller;

class Site extends Controller
{

    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }


}