<?php namespace App\HttpController\Api;

use App\HttpController\BaseController;

abstract class ApiBase extends BaseController
{
    public function index()
    {
        // TODO: Implement index() method.
        $this->actionNotFound('index');
    }

    protected function actionNotFound(?string $action)
    {
        parent::actionNotFound($action); // TODO: Change the autogenerated stub
    }

    public function onRequest(?string $action): ?bool
    {
        if (parent::onRequest($action)) {
            return false;
        }
        return true;
    }
    protected function onException(\Throwable $throwable): void
    {
       var_dump($throwable->getMessage());
    }
}